name: Deploy

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Foreman
      uses: actions/setup-foreman@v1
      with:
        version: "^1.1.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo build -o dist.rbxl
    - run: rbxcloud experience publish -f dist.rbxl -p ${{ SECRETS.DEV_PLACE_ID }}
    -u ${{ SECRETS.DEV_UNIVERSE_ID}} -t published -a ${{ SECRETS.API_KEY }}
