name: Deploy

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - uses: Roblox/setup-foreman@v2.1
      name: Install Foreman
      with:
        version: "^1.1.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Publish
      shell: bash
      run: rojo build -o dist.rbxlx && rbxcloud experience publish -f dist.rbxlx -t published -p ${{ SECRETS.DEV_PLACE_ID }} -u ${{ SECRETS.DEV_UNIVERSE_ID}} -a ${{ SECRETS.API_KEY }}
